/**
 * Turning a failed verdict into a lesson, deterministically.
 *
 * No model is anywhere in this decision path. The mapping below is a declared
 * table: one entry per validator issue code, written once, reviewable as text, and
 * producing the same lesson for the same failure every time. A code with no entry
 * proposes nothing — deliberately, and the omissions are listed with their reasons
 * rather than left as gaps someone later mistakes for oversights.
 *
 * The engine derives a lesson's id from its project, trigger, recommendation and
 * domain, and returns the existing one instead of writing a second. So proposing
 * on every failure is safe: the tenth time a build breaks on unresolved imports it
 * is the same lesson, not the tenth copy.
 */

/**
 * What every lesson from this table is and is not known to apply to.
 *
 * Stated on each one because the builder generates exactly one kind of project,
 * and a note that reads as universal advice will eventually be read as universal
 * advice.
 */
const LIMITS = [
    'Observed on Vite + React + TypeScript projects generated by this builder. Not verified anywhere else.',
];

/** Terms the recall layer matches lexically against the task it is asked about. */
const BUILD_SCOPE = ['build', 'generate', 'react', 'typescript', 'vite'];

/**
 * Issue code -> the lesson it justifies.
 *
 * Each recommendation has to survive being read alone, in a prompt, months from
 * now, by a model that has no idea what the validator is. So each says what to do
 * and why it matters, not which check fired.
 */
export const PROPOSAL_TABLE = {
    'unresolved-import': {
        trigger: 'A generated file imports a module that was never emitted',
        recommendation:
            'Before finishing, re-read every relative import you wrote and confirm the file it names is one you also emitted. ' +
            'Either emit the missing file or drop the import. An unresolved import fails the build outright — the rest of the project being correct does not help.',
    },
    'unbalanced-braces': {
        trigger: 'A generated file ends with unbalanced braces, so it was cut off before it finished',
        recommendation:
            'Finish each file before starting the next, and prefer several small files over one long one. ' +
            'A file that stops mid-expression fails the build even though everything written before it was right.',
    },
    'placeholder-content': {
        trigger: 'Generated code contains a placeholder where an implementation belongs',
        recommendation:
            'Write the real content everywhere. Never emit "// ... rest of the code", "TODO", "implementation goes here", or lorem ipsum. ' +
            'What you write is shipped exactly as written — a placeholder is a broken app, not a note to yourself.',
    },
    'invalid-json': {
        trigger: 'A generated .json file does not parse',
        recommendation:
            'Emit JSON strictly: no comments, no trailing commas, every key quoted. ' +
            'package.json and tsconfig.json are read by tools that reject anything else, so a single stray comma stops the install.',
    },
    'empty-file': {
        trigger: 'A generated file has no content at all',
        recommendation:
            'Do not list a path you are not going to fill. If a file turns out not to be needed, leave it out of the response entirely rather than emitting it empty.',
    },
    'missing-index-html': {
        trigger: 'index.html was not generated, so the project has no entry point',
        recommendation:
            'Always emit index.html, with a root element and a module script pointing at src/main.tsx. Without it nothing can start, however complete the rest is.',
    },
    'type-error': {
        trigger: 'Generated code failed a strict TypeScript check',
        recommendation:
            'Write code that type-checks under strict mode. Annotate props and state, ' +
            'do not assign across incompatible types, and do not reference identifiers ' +
            'that were never declared or imported.',
    },
    'syntax-error': {
        trigger: 'A generated file does not parse',
        recommendation:
            'Emit complete, syntactically valid files. Close every brace, bracket and JSX ' +
            'tag and terminate every string. Escape quotes inside JSX text — ' +
            'setQuote("I can\'t do this"), never setQuote(\'I can\'t do this\'). And never ' +
            'store code as data inside a template literal: a snippet containing a backtick ' +
            'or ${ ends the literal holding it and breaks the whole file. Use a ' +
            'double-quoted string with \\n, or escape every backtick and ${ in the content.',
    },
    'runtime-error': {
        trigger: 'The generated app threw once it was running',
        recommendation:
            'Guard every value that can be absent before you use it. Give useState a ' +
            'sensible initial value rather than null or undefined, check an array exists ' +
            'before mapping it, and do not read a property off something a fetch or a ' +
            'lookup might not have returned. Code that type-checks can still throw on ' +
            'the first render.',
    },
    'renders-nothing': {
        trigger: 'The app built and ran without error, but mounted nothing',
        recommendation:
            'Make sure the entry actually mounts: createRoot on the element index.html ' +
            'declares, rendering the app inside it. Then make sure the first route ' +
            'renders something — a router whose paths never match the initial location ' +
            'produces a page that is blank and not broken.',
    },
    'bundle-error': {
        trigger: 'The project would not bundle',
        recommendation:
            'Import only from files you emitted and packages you listed in package.json, ' +
            'and keep every module a valid ES module. A project that type-checks can ' +
            'still fail to build.',
    },
    'unresolved-html-ref': {
        trigger: 'index.html references a file that was never generated',
        recommendation:
            'Every src and href in index.html must name either a file you also emitted or an absolute external URL. A dangling local reference fails the build.',
    },
};

/**
 * Codes that describe a real failure but justify no lesson, and why.
 *
 * Kept as data rather than as silence: the difference between "we decided this
 * teaches nothing" and "nobody thought about it" is the whole value of a declared
 * table, and a new code arriving in neither map is a gap this file can be asked about.
 */
export const NOT_A_LESSON = {
    'no-files': 'The generator returned nothing. "Return some files" is not guidance a model can act on.',
    'missing-src-main': 'A warning, not a failure. The build still runs.',
    'file-too-short': 'A warning, and often correct — some files really are three lines.',
    /* These became errors when the plan stopped being a suggestion. They still teach
       nothing, but for a different reason than before: the manifest is now made to
       cover the plan before any request is spent (`coverPlan`), so by the time this
       fires the entry existed and the *file request* failed to deliver it. That is a
       generation gap, already carried by `missing`, and the lesson it would propose —
       "emit every page the plan names" — describes something the model was not given
       the chance to get wrong. */
    'plan-page-missing': 'The manifest is made to cover the plan, so this now means a file request failed, not that the model forgot the page.',
    'plan-component-missing': 'The same: a delivery gap, not a planning one.',
};

/** Any code the table has never been asked about — the thing this file exists to surface. */
export function unmappedCodes(codes) {
    return Object.keys(codes ?? {}).filter(
        (code) => !(code in PROPOSAL_TABLE) && !(code in NOT_A_LESSON),
    );
}

/**
 * The lessons a verdict justifies. Pure: no I/O, no clock, no engine.
 *
 * A passing verdict justifies none — a build that worked teaches nothing about
 * what to avoid, and proposing from it would fill the ladder with notes no failure
 * ever motivated.
 */
export function proposalsFor(payload) {
    if (!payload || payload.ok !== false) return [];
    /**
     * An instrument that failed has no opinion about the work.
     *
     * When a generation is cut off by its output budget, the validators run over a
     * half-written project and report exactly what you would expect: unbalanced
     * braces, unterminated strings, a missing entry point. Every one of those is true
     * of the *text* and false of the *model* — it did not forget `index.html`, it was
     * stopped before it got there.
     *
     * Proposing from that teaches the next attempt to fix mistakes nobody made, and a
     * single passing build afterwards promotes the lie to `qualified`. Measured on a
     * real build: three lessons, all three wrong, all three from one truncation.
     *
     * So an inconclusive verdict proposes nothing. It is not a pass and not a
     * failure; it is the absence of a verdict, and the ladder must be told so.
     */
    if (payload.inconclusive === true) return [];

    const codes = payload.codes ?? {};
    return Object.keys(codes)
        .filter((code) => code in PROPOSAL_TABLE)
        .sort()   // declared order, so two identical verdicts propose identically
        .map((code) => ({
            code,
            trigger: PROPOSAL_TABLE[code].trigger,
            recommendation: PROPOSAL_TABLE[code].recommendation,
            scope: BUILD_SCOPE,
            domain: 'build',
            limits: LIMITS,
            triggerTags: ['builder', code],
        }));
}
