/**
 * Express GitHub OAuth Closure Factory
 * Provides standalone GitHub OAuth login, callback, session verification,
 * and route protection middleware using pure HTTP/standard crypto.
 */
import crypto from 'crypto';

export function createGithubAuthManager({
    clientId = process.env.GITHUB_CLIENT_ID,
    clientSecret = process.env.GITHUB_CLIENT_SECRET,
    redirectUri = process.env.GITHUB_REDIRECT_URI || 'http://localhost:8050/api/auth/github/callback',
    jwtSecret = process.env.JWT_SECRET || 'dev-secret-change-in-prod-32-chars-min',
    allowedUsers = (process.env.ALLOWED_GITHUB_USERS || '').split(',').map(u => u.trim().toLowerCase()).filter(Boolean),
    cookieName = 'multi_app_session',
    stateCookieName = 'multi_app_oauth_state',
    stateMaxAgeMs = 10 * 60 * 1000,
} = {}) {
    /**
     * This provider mints a session under the **same cookie name and the same signing
     * secret** as the Google one, so a token it issues is a token `requireAuth`
     * accepts. That makes it a second door to one lock — and its allowlist defaulted to
     * empty, which this codebase reads as "admit everyone".
     *
     * Google's allowlist would have been irrelevant: sign in with any GitHub account,
     * receive a session the Google-side middleware honours. So it refuses to exist
     * without an allowlist, rather than warning about one.
     */
    if (!clientId || !clientSecret) {
        throw new Error('[GithubAuth] GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET are required to mount this provider');
    }
    if (!allowedUsers.length) {
        throw new Error(
            '[GithubAuth] ALLOWED_GITHUB_USERS is empty. This provider issues sessions under the same '
            + 'cookie and secret as Google, so an empty allowlist here admits every GitHub account to '
            + 'the whole app regardless of ALLOWED_EMAILS.',
        );
    }

    function sameSecret(a, b) {
        if (typeof a !== 'string' || typeof b !== 'string') return false;
        return crypto.timingSafeEqual(
            crypto.createHash('sha256').update(Buffer.from(a)).digest(),
            crypto.createHash('sha256').update(Buffer.from(b)).digest(),
        );
    }

    function parseCookies(req) {
        const list = {};
        const rc = req.headers.cookie;
        if (!rc) return list;
        rc.split(';').forEach(cookie => {
            const parts = cookie.split('=');
            const name = parts.shift().trim();
            try { list[name] = decodeURIComponent(parts.join('=')); }
            catch { list[name] = parts.join('='); }
        });
        return list;
    }

    function base64UrlEncode(str) {
        return Buffer.from(str)
            .toString('base64')
            .replace(/=/g, '')
            .replace(/\+/g, '-')
            .replace(/\//g, '_');
    }

    function base64UrlDecode(str) {
        str = str.replace(/-/g, '+').replace(/_/g, '/');
        while (str.length % 4) str += '=';
        return Buffer.from(str, 'base64').toString('utf8');
    }

    function signToken(payload, expiresInSeconds = 7 * 86400) {
        const header = { alg: 'HS256', typ: 'JWT' };
        const now = Math.floor(Date.now() / 1000);
        const fullPayload = { ...payload, iat: now, exp: now + expiresInSeconds };
        const encHeader = base64UrlEncode(JSON.stringify(header));
        const encPayload = base64UrlEncode(JSON.stringify(fullPayload));
        const signature = crypto
            .createHmac('sha256', jwtSecret)
            .update(`${encHeader}.${encPayload}`)
            .digest('base64')
            .replace(/=/g, '')
            .replace(/\+/g, '-')
            .replace(/\//g, '_');
        return `${encHeader}.${encPayload}.${signature}`;
    }

    /** Required, not defaulted — see the Google module for why a caller-chosen nonce is not one. */
    function getAuthUrl(state) {
        if (!state) throw new Error('getAuthUrl requires a state generated by newState()');
        const params = new URLSearchParams({
            client_id: clientId,
            redirect_uri: redirectUri,
            scope: 'read:user user:email',
            state,
        });
        return `https://github.com/login/oauth/authorize?${params.toString()}`;
    }

    const newState = () => crypto.randomBytes(32).toString('hex');

    async function handleCallback(code) {
        // 1. Exchange code for access_token
        const tokenResp = await fetch('https://github.com/login/oauth/access_token', {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                client_id: clientId,
                client_secret: clientSecret,
                code,
                redirect_uri: redirectUri
            })
        });

        const tokenData = await tokenResp.json();
        if (tokenData.error) {
            throw new Error(`GitHub token exchange failed: ${tokenData.error_description || tokenData.error}`);
        }

        const accessToken = tokenData.access_token;

        // 2. Fetch user profile
        const userResp = await fetch('https://api.github.com/user', {
            headers: {
                'Authorization': `Bearer ${accessToken}`,
                'User-Agent': 'multi-app-auth'
            }
        });
        if (!userResp.ok) throw new Error('Failed to fetch GitHub profile');
        const profile = await userResp.json();

        // 3. Fetch primary email if not visible in public profile
        let email = profile.email;
        if (!email) {
            const emailResp = await fetch('https://api.github.com/user/emails', {
                headers: {
                    'Authorization': `Bearer ${accessToken}`,
                    'User-Agent': 'multi-app-auth'
                }
            });
            if (emailResp.ok) {
                const emails = await emailResp.json();
                const primary = emails.find(e => e.primary) || emails[0];
                if (primary) email = primary.email;
            }
        }

        // 4. Access control
        const username = (profile.login || '').trim().toLowerCase();
        if (allowedUsers.length > 0 && !allowedUsers.includes(username)) {
            const err = new Error(`GitHub user ${username} is not authorized for access.`);
            err.code = 'FORBIDDEN';
            throw err;
        }

        const user = {
            id: String(profile.id),
            username: profile.login,
            name: profile.name || profile.login,
            email: email,
            avatar_url: profile.avatar_url,
            provider: 'github'
        };

        const sessionToken = signToken({ user });
        return { user, sessionToken, accessToken };
    }

    function attachRoutes(router, { successRedirect = '/' } = {}) {
        router.get('/api/auth/github', (req, res) => {
            const state = newState();
            res.cookie(stateCookieName, state, {
                httpOnly: true,
                sameSite: 'lax',
                secure: process.env.NODE_ENV === 'production',
                path: '/',
                maxAge: stateMaxAgeMs,
            });
            res.redirect(getAuthUrl(state));
        });

        router.get('/api/auth/github/callback', async (req, res) => {
            const { code, error, state } = req.query;
            const sent = parseCookies(req)[stateCookieName];
            res.clearCookie(stateCookieName, { path: '/' });

            if (error) return res.status(400).send(`GitHub OAuth error: ${error}`);
            /* Before the code is spent: an unsolicited callback must cost nothing. */
            if (!sent || !state || !sameSecret(String(sent), String(state))) {
                return res.status(400).send('GitHub OAuth error: this sign-in was not started here');
            }
            if (!code) return res.status(400).send('Missing authorization code');

            try {
                const { sessionToken } = await handleCallback(code);
                res.cookie(cookieName, sessionToken, {
                    httpOnly: true,
                    sameSite: 'lax',
                    secure: process.env.NODE_ENV === 'production',
                    path: '/',
                    maxAge: 7 * 86400 * 1000
                });
                res.redirect(successRedirect);
            } catch (err) {
                console.error('[GithubAuth] Callback error:', err.message);
                if (err.code === 'FORBIDDEN') {
                    return res.status(403).send(`<h3>Access Denied</h3><p>${err.message}</p>`);
                }
                res.status(500).send(`<h3>Authentication Failed</h3><p>${err.message}</p>`);
            }
        });

        return router;
    }

    return {
        getAuthUrl,
        handleCallback,
        attachRoutes
    };
}
